name: practise2

on: 
    workflow_dispatch:
        inputs:
            number1:
                description: 'First Number'
                default: '0'
                required: false
env:
      myName: Panna
jobs: 
  practise1:

    runs-on: ubuntu-latest

    

    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"

  practise2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$myName"
      - run: echo "${{vars.Project_ID}}"
      - run: echo "${{github.repository}}"
      - run: echo "${{github.workflow}}"
      - run: echo "${{github.triggering_actor}}"

  practise3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$myName"
      - run: echo "${{vars.Project_ID}}"
      - run: echo "${{inputs.number1}}"
  
